# This is a basic workflow to help you get started with Actions

name: Download tasks

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          lfs: true

      - run: |
          Invoke-Expression "& { $(irm https://aka.ms/install-powershell.ps1) } -UseMSI -preview -quiet"
          "C:\Program Files\PowerShell\7-preview" >> $env:GITHUB_PATH
        name: Upgrade to latest preview of powershell 
        # https://github.com/PowerShell/PowerShell/issues/17404#issuecomment-1188348379

      # Runs a single command using the runners shell
      - run: |
          .\build.ps1
        shell: pwsh
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name: Download tasks and build side-by-side versions.

      - uses: marvinpinto/action-automatic-releases@latest
        name: Create GitHub release
        if: env.TAG != ''
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ env.TAG }}
          prerelease: false
          title: ${{ env.TAG }}
          files: |
            ./_download/*.zip
            ./_sxs/*.zip
            ./_vsix/*.vsix

      - uses: tubone24/update_release@v1.3.1
        name: Update release notes
        if: env.TAG != ''
        with:
          body_path: releasenote.template.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
          TAG_NAME: ${{ env.TAG }}

      - run: |
          & npm install tfx-cli@latest --location=global
          foreach ($vsix in dir ./_vsix/*.vsix)
          {
            & tfx extension publish --vsix $vsix.FullName --token $env:AZURE_MARKETPLACE_PAT
          }
        shell: pwsh
        name: Publish extensions
        if: env.TAG != ''
        env:
          AZURE_MARKETPLACE_PAT: ${{ secrets.AZURE_MARKETPLACE_PAT }}
